name: test
on: [push, pull_request]

jobs:
  cargo_bloat_example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
